citesphere/src/main/java/edu/asu/diging/citesphere/core/export/impl/ExportManager.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/export/impl/ExportProcessor.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/export/proc/impl/CsvProcessor.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/model/export/impl/ExportTask.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/repository/export/ExportTaskRepository.java, citesphere/src/main/webapp/WEB-INF/views/auth/group/editItem.jsp, citesphere/src/test/java/edu/asu/diging/citesphere/core/export/impl/ExportManagerTest.java
and renamed export task counter
=> [CITE-44] fixed first/last name bug

citesphere/src/main/java/edu/asu/diging/citesphere/config/core/AuditConfig.java, citesphere/src/main/java/edu/asu/diging/citesphere/config/core/CitesphereConfig.java, citesphere/src/main/java/edu/asu/diging/citesphere/config/core/CitesphereConnectionSignUp.java, citesphere/src/main/java/edu/asu/diging/citesphere/config/core/CsrfSecurityRequestMatcher.java, citesphere/src/main/java/edu/asu/diging/citesphere/config/core/CustomAuthenticationFailureHandler.java, citesphere/src/main/java/edu/asu/diging/citesphere/config/core/KafkaConfig.java, citesphere/src/main/java/edu/asu/diging/citesphere/config/core/PersistentContext.java, citesphere/src/main/java/edu/asu/diging/citesphere/config/core/SecurityContext.java, citesphere/src/main/java/edu/asu/diging/citesphere/config/core/SimpleSignInAdapter.java, citesphere/src/main/java/edu/asu/diging/citesphere/config/core/ZoteroConfig.java, citesphere/src/main/java/edu/asu/diging/citesphere/config/web/SocialContext.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/kafka/impl/KafkaRequestProducer.java, citesphere/src/main/java/edu/asu/diging/citesphere/web/HomeController.java, citesphere/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, citesphere/src/main/webapp/WEB-INF/spring/root-context.xml
* [CITE-50] fix issue with provider controller not found
moved social configs to servlet context
* [CITE-50] removed unused exceptions thrown
=> Bug/cite 50 (#47)

citesphere/pom.xml, citesphere/src/main/java/edu/asu/diging/citesphere/core/model/authority/impl/AuthorityEntry.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/model/bib/impl/Affiliation.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/model/bib/impl/Citation.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/model/bib/impl/CitationConcept.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/model/bib/impl/CitationConceptTag.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/model/bib/impl/ConceptType.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/model/bib/impl/Person.java
Added the required updates on tables/columns: https://diging.atlassian.net/wiki/spaces/CITED/pages/1347878913/Converting+MySQL+to+UTF8mb4+encoding+to+handle+special+characters+Example
=> [CITE-65] Modify pom to instruct database source to use unicode.

citesphere/src/main/java/edu/asu/diging/citesphere/config/core/SecurityContext.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/model/oauth/impl/DbAccessToken.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/model/oauth/impl/DbRefreshToken.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/model/oauth/impl/SerializableObjectConverter.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/repository/oauth/DbAccessTokenRepository.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/repository/oauth/DbRefreshTokenRepository.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/DbTokenStore.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/oauth/GrantTypes.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/oauth/impl/OAuthClientManager.java, citesphere/src/main/java/edu/asu/diging/citesphere/web/admin/oauth/AddOAuthClientController.java
refresh token are returned in authorization_code workflow
=> [CITE-75] tokens are perstisted to DB

citesphere/src/main/webapp/WEB-INF/views/auth/group/item.html
CITE - 69 - There is no ';' between editors (and presumably between other contributors as well)
Fixed the issue for authors and contributors.
=> [CITE - 69] - Added the semi colon for authors and translators

citesphere/pom.xml, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/IAuthorityService.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/AuthorityService.java, citesphere/src/main/java/edu/asu/diging/citesphere/web/user/AuthoritySearchResult.java, citesphere/src/main/java/edu/asu/diging/citesphere/web/user/authorities/AuthorityEntryController.java, citesphere/src/main/java/edu/asu/diging/citesphere/web/user/authorities/AuthorityListController.java, citesphere/src/main/webapp/WEB-INF/views/auth/authorities/list.html, citesphere/src/main/webapp/WEB-INF/views/auth/group/editItem.html
The group should be a citation group. Every user that has access to a group should be able to add/edit/delete authorities from that group. When a new authority is created a user should choose if that authority would be part of the citation group it is being created for (default) or just available to the user (no group).
An authority can belong to more than one group.
The "Manage Authority Entries" page should show the authorities categorized by group. E.g. a user would select a group and then see all authorities in that group. …
=> [CITE-134] Add group to Authority Entry

citesphere/src/main/java/edu/asu/diging/citesphere/web/user/SearchController.java
[CITE-152] - Search in group: if there are no results, the search bar breaks
[CITE-152]: https://diging.atlassian.net/browse/CITE-152
=> [CITE-152] - Fixed bug for search icon on empty search result

citesphere/src/test/java/edu/asu/diging/citesphere/core/service/impl/AuthorityServiceTest.java
[CITE-160] Test case needs fixing: AuthorityServiceTest -> test_createWithURI
=> [CITE-160] - Fixed test case

citesphere/src/main/resources/log4j2.xml, citesphere/src/test/java/edu/asu/diging/citesphere/core/service/impl/AuthorityServiceTest.java
Co-authored-by: Maulik Vajubhai Limbadiya (Student) <mlimbadi@sundevils.asu.edu>
...Put description here...
=> [CITE-160] - Fixed test case (#171)

citesphere/src/main/webapp/WEB-INF/views/auth/group/item.html
CITE-169 
...Put description here...
When we are viewing first citation, previous button should be disabled and non clickable since there wont be any previous citations and when we are viewing last citation , next button should be disabled and non clickable.
=> CITE-169 Disable button when previous and next citations are not present

citesphere/pom.xml
...Put description here...
[CITE-166] updating log4j version to 2.17.1 in citesphere/pom.xml 
[CITE-166]: https://diging.atlassian.net/browse/CITE-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CITE-166] Update log4j from 2.11.1 to 2.17.1

citesphere/pom.xml, citesphere/src/main/webapp/WEB-INF/views/auth/group/items.html
Column to show if an item has file attached.
On the items page there needs to be a column that shows if an item has files attached.
I have used icon-multiple-doc icon for showing the file is attached or not.
=> CITE-165 Added a File Column in Items page.

citesphere/src/main/webapp/WEB-INF/views/auth/group/editItem.html
Add icon for authors, editors, etc. on edit item page is missing
=> [CITE-155] Added styles to .icon-circle-add for all the add features

citesphere/pom.xml, citesphere/src/main/java/org/springframework/security/core/authority/SimpleGrantedAuthority.java, citesphere/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Upgrade to spring security 5.3.3
=> [CITE-153] Upgrade to spring security 5.3.3

citesphere/pom.xml, citesphere/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
https://diging.atlassian.net/browse/CITE-181
Upgrade spring security version from 5.3.10.RELEASE to 5.5.7
=> [CITE-181] Upgrade spring security version

citesphere/src/main/java/edu/asu/diging/citesphere/web/user/ItemController.java, citesphere/src/main/webapp/WEB-INF/views/auth/group/item.html
https://diging.atlassian.net/browse/CITE-193
Added group name in the breadcrumb of the citations details page.
=> Updated group name in citation details page

citesphere/src/main/java/edu/asu/diging/citesphere/core/model/oauth/IOAuthClient.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/model/oauth/impl/OAuthClient.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/oauth/IOAuthClientManager.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/oauth/impl/OAuthClientManager.java, citesphere/src/main/java/edu/asu/diging/citesphere/web/admin/oauth/AddOAuthClientController.java, citesphere/src/main/java/edu/asu/diging/citesphere/web/admin/oauth/OAuthClientDetailsController.java, citesphere/src/main/webapp/WEB-INF/views/admin/apps/details.html, citesphere/src/main/webapp/WEB-INF/views/admin/apps/show.html, citesphere/src/test/java/edu/asu/diging/citesphere/core/service/oauth/impl/OAuthClientManagerTest.java
https://diging.atlassian.net/browse/CITE-216
=> [CITE-216] Store user info for app creation

citesphere/src/main/webapp/WEB-INF/views/auth/group/item.html
The url shown on the citation page, isn’t actually linking to the url.
https://diging.atlassian.net/browse/CITE-198
=> Bug/CITE-198: The url of citations isn't generated correctly.

citesphere/src/main/java/edu/asu/diging/citesphere/core/model/oauth/impl/OAuthClient.java
Citesphere seems to delete user accounts after too many API requests
@Girik Manchanda has experienced that issue
https://diging.atlassian.net/browse/CITE-224
=> bug/CITE-224 - Citesphere seems to delete user accounts after too many API requests

citesphere/pom.xml, citesphere/src/main/java/edu/asu/diging/citesphere/api/v1/user/CheckAccessController.java, citesphere/src/main/java/edu/asu/diging/citesphere/config/core/SecurityContext.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/repository/oauth/DbAccessTokenRepository.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/ICitationStore.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/giles/impl/UploadResponse.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/CitationStore.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/DbTokenStore.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/oauth/InternalTokenManager.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/oauth/impl/InternalTokenManagerImpl.java
=> [GECO-145] work with tokens and access control checks for progress ids

citesphere/pom.xml, citesphere/src/main/java/edu/asu/diging/citesphere/config/core/SecurityContext.java, citesphere/src/main/java/edu/asu/diging/citesphere/core/service/oauth/impl/OAuthClientManager.java
=> Trying to fix token expire in issue
